const images = [
   {"url" : "../ART/blackonblack/sodmgweb.png", "label": "money counter, fuck a bank, 2021"},
   {"url" : "../ART/blackonblack/ciggieweb.png", "label": "liberty pack, 2021"},
   {"url" : "../ART/blackonblack/gorlweb.png", "label": "flower girl, 2021"},
   {"url" : "../ART/blackonblack/sldweb.png", "label": "senor love daddy, 2021"},
   {"url" : "../ART/blackonblack/squillsweb.png", "label": "454 - pisces, 2021"},
   {"url" : "../ART/blackonblack/screaminweb.png", "label": "screamin, 2021"},
   {"url" : "../ART/blackonblack/moodweb.png", "label": "telephone moods, 2021"},
   {"url" : "../ART/blackonblack/bigbattygyal.png", "label": "big batty gyal, 2021"},
   {"url" : "../ART/blackonblack/call.png", "label": "watts - freddie gibbs & madlib, 2021"},
   {"url" : "../ART/blackonblack/bopbop.png", "label": "the shooter, 2021"},
   {"url" : "../ART/blackonblack/cheadleshot.png", "label": "the shot, 2021"},
   {"url" : "../ART/blackonblack/kickthatbeat.png", "label": "kick that beat, 2021"},
   {"url" : "../ART/blackonblack/homies.png", "label": "the homies, 2021"},
   {"url" : "../ART/blackonblack/bronxdj.png", "label": "wheelz of steel, 2021"},
   {"url" : "../ART/blackonblack/menma.png", "label": "me n' ma, 2021"},
   {"url" : "../ART/blackonblack/realdads.png", "label": "real dads, 2021"},
   {"url" : "../ART/blackonblack/spade.png", "label": "re-nigg, 2021"},
   {"url" : "../ART/blackonblack/eercut.png", "label": "eercut, 2021"},
   {"url" : "../ART/blackonblack/nyc.png", "label": "who is you, 2021"},
   {"url" : "../ART/blackonblack/blcklve.png", "label": "union, 2021"},
   {"url" : "../ART/blackonblack/dancer.png", "label": "shimmy, 2021"},
   {"url" : "../ART/blackonblack/rza.png", "label": "rza razor sharp, 2021"},
   {"url" : "../ART/blackonblack/pappy.png", "label": "pops, 2021"},
   {"url" : "../ART/blackonblack/bleck.png", "label": "pops again, 2021"},
   {"url" : "../ART/blackonblack/smoke.png", "label": "clout goggles, 2021"},

]
